site_name: Matillion Docs
nav:
  - Home: 'index.md'
  - Unlimited Scale:
    - Overview: unlimited-scale/index.md
    - Get started:
        - Create an ETL agent: unlimited-scale/create-an-etl-agent.md
        - Add ETL agent credentials to AWS Secrets Manager : unlimited-scale/add-etl-agent-credentials-to-aws-secrets-manager.md
        - AWS Fargate manual agent setup: unlimited-scale/aws-fargate-manual-agent-setup.md
        - Editing Permissions for Unlimited Scale: unlimited-scale/editing-permissions-for-unlimited-scale.md
        - Running Matillion ETL jobs with Unlimited Scale: unlimited-scale/running-matillion-etl-jobs-with-unlimited-scale.md
  - Matillion Custom Connector:
    - Overview: mcc/index.md
    - Get started:
        - Custom Connector Setup: mcc/custom-connector-setup.md
        - Authentication: mcc/manage-oauths.md
        - Exporting your own connector to Matillion ETL: mcc/exporting-your-own-connector-to-matillion-etl.md

    


theme: 
  name: 'material'
  palette:
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/white-logo.svg
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/shortcuts.js

copyright: Copyright &copy; 2022 - Matillion

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra:
  generator: false
